name: Check for new Ubuntu image

on:
  schedule:
    - cron:  '12 19 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  check_image_hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull ubuntu:24.04

      - name: Get current hash
        run: |
          CURRENT_HASH=$(docker save ubuntu:24.04 | tar -xO | shasum -a 256 | cut -d' ' -f1)
          echo "CURRENT_HASH=$CURRENT_HASH" >> $GITHUB_ENV

      - name: Get previous hash
        id: get_previous_hash
        run: |
          PREVIOUS_HASH=$(cat upstream-releases/ubuntu_hash.txt)
          echo "PREVIOUS_HASH=$PREVIOUS_HASH" >> $GITHUB_ENV

      - name: Compare hashes
        id: compare_hashes
        run: |
          if [ -n "${{ env.PREVIOUS_HASH }}" ]; then
            if [ "${{ env.PREVIOUS_HASH }}" = "${{ env.CURRENT_HASH }}" ]; then
              echo "Hashes match. No change detected."
              echo "MODIFIED=false" >> $GITHUB_ENV
            else
              echo "Hashes differ. There's a change in the image."
              echo "${{ env.CURRENT_HASH }}" > upstream-releases/ubuntu_hash.txt
              echo "MODIFIED=true" >> $GITHUB_ENV
            fi
          else
            echo "Previous hash not found. This is likely the first run."
            echo "${{ env.CURRENT_HASH }}" > upstream-releases/ubuntu_hash.txt
          fi
      - name: Commit latest hash
        if: env.MODIFIED == 'true'
        run: |
          git config --global user.name 'hucknz'
          git config --global user.email '12265772+hucknz@users.noreply.github.com'
          git commit -am "New Ubuntu hash found"
          git push